name: LIZItensEspeciais
version: '2.1'
main: br.com.henriplugins.LIZItensEspeciais
api-version: '1.19'
depend: [ItemsAdder, AuraSkills, Vault]
commands:
  lizitem:
    description: Dá um item especial para um jogador
    usage: /lizitem <nick> <quantia> <item>
    permission: lizitensespeciais.lizitem